export type Product = {
  id: string;
  slug: string;
  name: string;
  description: string;
  price: number;
  images: string[];
  category: string;
  collection: string;
  features: string[];
  details: string;
  shipping: string;
  warranty: string;
};

export const dummyProducts: Product[] = [
  {
    id: "p1",
    slug: "chocolate-caliente-starsex",
    name: "Chocolate Caliente Starsex",
    description: "Lubricante 4 en 1 Efecto Calor Sachet 5 ml. Una experiencia cálida y dulce.",
    price: 3500,
    images: [],
    category: "Lubricantes y Aceites",
    collection: "Starsex Essentials",
    features: ["Efecto Calor", "Sabor Chocolate", "Base Agua", "Comestible"],
    details: "Despierta tus sentidos con este lubricante 4 en 1 que combina el delicioso sabor del chocolate caliente con un excitante efecto calor.",
    shipping: "Envío discreto. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p2",
    slug: "lubricante-retardante-masculino-starsex",
    name: "Lubricante Retardante Masculino Starsex",
    description: "Sachet 5 ml. Control y resistencia prolongada.",
    price: 3500,
    images: [],
    category: "Cuidado Masculino",
    collection: "Starsex Performance",
    features: ["Efecto Retardante", "Acción Rápida", "Seguro con Preservativos"],
    details: "Mejora el rendimiento y prolonga el placer con esta fórmula especializada que desensibiliza ligeramente para mayor duración.",
    shipping: "Envío discreto. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p3",
    slug: "choco-lub-starsex",
    name: "Choco Lub Starsex",
    description: "Sachet 5 ml – Lubricante Íntimo Sabor Chocolate.",
    price: 3500,
    images: [],
    category: "Lubricantes y Aceites",
    collection: "Starsex Flavors",
    features: ["Sabor Intenso", "Base Agua", "Seguro y Comestible"],
    details: "Un lubricante clásico base agua con un irresistible y auténtico sabor a chocolate, ideal para juegos previos.",
    shipping: "Envío discreto. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p4",
    slug: "fruti-lub-starsex",
    name: "Fruti Lub Starsex",
    description: "Lubricante 4 en 1 Efecto Calor Frutilla Sachet 5 ml.",
    price: 3500,
    images: [],
    category: "Lubricantes y Aceites",
    collection: "Starsex Flavors",
    features: ["Efecto Calor", "Sabor Frutilla", "Base Agua", "Comestible"],
    details: "La combinación perfecta entre el dulce sabor a frutilla y un emocionante efecto calor que estimula las zonas íntimas.",
    shipping: "Envío discreto. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p5",
    slug: "kit-suave-sumision-starsex-rojo",
    name: "Kit Suave Sumisión Starsex (Rojo)",
    description: "Explora la pasión y el control con este set de iniciación.",
    price: 24900,
    images: [],
    category: "Kits y Juegos",
    collection: "BDSM Suave",
    features: ["Material Suave", "Color Rojo Pasión", "Ajustable", "Fácil de Usar"],
    details: "Un kit de introducción al bondage diseñado con materiales suaves que garantizan seguridad y comodidad durante la exploración.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía por defectos de fábrica."
  },
  {
    id: "p6",
    slug: "plug-metalico-kitty-s",
    name: "Plug Metálico Kitty S",
    description: "Elegancia y peso en un diseño compacto con detalle de joya.",
    price: 15900,
    images: [],
    category: "Juguetes Anal",
    collection: "Luxury Metal",
    features: ["Aleación de Aluminio", "Joya Incrustada", "Sensibilidad Térmica", "Tamaño S"],
    details: "Ideal para principiantes, este plug metálico puede calentarse o enfriarse en agua para sensaciones térmicas únicas.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p7",
    slug: "feromona-enamor-starsex-masculina-30ml",
    name: "Feromona Enamor Starsex Masculina",
    description: "30ml de atracción y magnetismo puro.",
    price: 19900,
    images: [],
    category: "Cosmética Sensorial",
    collection: "Atracción Química",
    features: ["Alta Concentración", "Aroma Sutil", "Efecto Prolongado", "Uso Diario"],
    details: "Fragancia formulada con feromonas de alta calidad para potenciar el atractivo natural y la confianza masculina.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p8",
    slug: "set-anillos-pene-donuts-starsex",
    name: "Set de Anillos para Pene Donuts Starsex",
    description: "Mejora y prolonga la firmeza con comodidad.",
    price: 12900,
    images: [],
    category: "Cuidado Masculino",
    collection: "Starsex Performance",
    features: ["Silicona Flexible", "Diferentes Diámetros", "Fáciles de Poner", "Mejora la Erección"],
    details: "Set de anillos elásticos y cómodos diseñados para restringir suavemente el flujo sanguíneo y aumentar el rendimiento.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía por defectos de fábrica."
  },
  {
    id: "p9",
    slug: "bolas-chinas-vibradoras-inalambricas-starsex",
    name: "Bolas Chinas Vibradoras e Inalámbricas",
    description: "Entrenamiento pélvico y estimulación profunda con control remoto.",
    price: 34900,
    images: [],
    category: "Vibradores",
    collection: "Kegel & Pleasure",
    features: ["Control Remoto", "Varios Modos", "Sumergibles", "Silicona Médica"],
    details: "Combina los ejercicios de Kegel tradicionales con potentes vibraciones controlables a distancia para un placer dual.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "1 año de garantía por problemas eléctricos."
  },
  {
    id: "p10",
    slug: "kit-de-sade-starsex",
    name: "Kit de Sade Starsex",
    description: "Para los amantes del juego de roles y la dominación total.",
    price: 39900,
    images: [],
    category: "Kits y Juegos",
    collection: "BDSM Premium",
    features: ["Set Completo", "Cuero Ecológico", "Acabados Metálicos", "Alta Resistencia"],
    details: "El set definitivo para llevar las fantasías BDSM a la realidad, incluyendo accesorios premium para ataduras y estimulación sensorial.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía por defectos de fábrica."
  },
  {
    id: "p11",
    slug: "kit-bdsm-10-piezas-starsex",
    name: "Kit BDSM 10 Piezas Starsex",
    description: "Llega a Sexshopmayorista el nuevo y completo Kit BDSM 10 Piezas Starsex, diseñado para llevar tus juegos de rol y prácticas de dominación y sumisión a un nivel superior. Este set incluye 10 accesorios pensados para explorar el mundo del BDSM de forma segura, placentera y estimulante, intensificando la conexión y la pasión entre parejas.",
    price: 19990,
    images: [],
    category: "Kits y Juegos",
    collection: "BDSM Premium",
    features: ["10 Accesorios", "Inmovilizadoras", "Mordaza", "Látigo", "Seguro y Consensuado"],
    details: "Con este kit podrás cumplir todas tus fantasías gracias a las inmovilizadoras de manos y pies, mordaza, segadera, cuerda para nudos, látigo, pinzas para pezones y collar con correa. Cada accesorio está pensado para agudizar los sentidos y disfrutar sesiones de roles extremas de manera segura y consensuada.",
    shipping: "Envío discreto en 24/48h. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía por defectos de fábrica."
  },
  {
    id: "p12",
    slug: "aceite-masaje-kama-sutra-sex-magnet",
    name: "Aceite de Masaje Kama Sutra con Feromonas SEX MAGNET",
    description: "Aceite de masaje sensual infundido con feromonas para atraer.",
    price: 6495,
    images: [],
    category: "Cosmética Sensorial",
    collection: "Kama Sutra",
    features: ["Aroma Atrayente", "Feromonas Femeninas/Masculinas", "Suave al Tacto", "No pegajoso"],
    details: "Despierta el deseo y mejora la conexión íntima. Especialmente formulado con feromonas para potenciar el magnetismo personal. Ideal para masajes prolongados.",
    shipping: "Envío discreto. Empaque sin logos ni referencias al contenido.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p13",
    slug: "satisfyer-curvy-1-plus",
    name: "Satisfyer c/ pulso de aire Curvy 1 +",
    description: "Estimulador de clítoris por ondas de presión y vibración simultánea, con control por App.",
    price: 28495,
    images: [],
    category: "Vibradores",
    collection: "Satisfyer Premium",
    features: ["Ondas de Presión", "Control por App", "Sumergible IPX7", "Recargable"],
    details: "Diseño ergonómico con tecnología Air Pulse y vibración intensa. Compatible con la app Satisfyer Connect para crear tus propias vibraciones o controlar a distancia.",
    shipping: "Envío discreto rápido. Caja cerrada.",
    warranty: "Garantía de fabricante."
  },
  {
    id: "p14",
    slug: "satisfyer-pro-2-generation-2",
    name: "Satisfyer Pro 2 Generation 2",
    description: "El aclamado estimulador clitorial de ondas de presión, ahora más silencioso y potente.",
    price: 29995,
    images: [],
    category: "Vibradores",
    collection: "Satisfyer Premium",
    features: ["Ondas de Presión 11 Niveles", "Súper Silencioso", "Resistente al agua IPX7", "Motor potente"],
    details: "El clásico reinventado. Estimulación del clítoris sin contacto usando excitantes ondas de presión que conducen a clímax múltiples y profundos.",
    shipping: "Envío discreto. Empaque sin logos.",
    warranty: "1 Año de Garantía."
  },
  {
    id: "p15",
    slug: "vibrador-conejo-empuje-perlas-vibratorias",
    name: "Vibrador Conejo con Empuje y Perlas Vibratorias Giratorias",
    description: "Doble estimulación: vaginal con empuje/rotación y clitorial (Rabbit).",
    price: 24995,
    images: [],
    category: "Vibradores",
    collection: "Rabbit Deluxe",
    features: ["Función de Empuje", "Rotación de perlas 360", "Silicona Médica", "Múltiples Modos"],
    details: "Sumérgete en un éxtasis completo. Mientras el eje interno empuja y hace rotar perlas en tu interior, las orejas de conejo proporcionan una estimulación clitorial directa.",
    shipping: "Empaque oscuro. Discreción total.",
    warranty: "Garantía de calidad Silk Deluxe."
  },
  {
    id: "p16",
    slug: "kit-secretos-geisha-frutilla-shunga",
    name: "Kit Secretos de la Geisha Frutilla Shunga",
    description: "Exquisito set cosmético de la famosa marca Shunga, sabor a frutilla.",
    price: 16250,
    images: [],
    category: "Kits y Juegos",
    collection: "Shunga Lovers",
    features: ["Aceites y Cremas", "Sabor Frutilla", "Calidad Premium", "Set para Parejas"],
    details: "Inspirado en el arte erótico japonés. Incluye cosméticos íntimos, polvos corporales y aceites besables para convertir el cuerpo en un auténtico postre.",
    shipping: "Envío discreto y seguro.",
    warranty: "Garantía Silk Deluxe."
  },
  {
    id: "p17",
    slug: "anillo-vibrador-descartable-vibra-hole",
    name: "Anillo Vibrador Descartable Vibra-Hole",
    description: "Anillo elastizado desechable con dispositivo de vibración.",
    price: 2750,
    images: [],
    category: "Cuidado Masculino",
    collection: "Accesorios Rápidos",
    features: ["Bala vibratoria", "Uso único o limitado", "Económico", "Talla Única"],
    details: "Perfecto para probar nuevas sensaciones o para un viaje rápido. Se adapta cómodamente a la base del pene brindando vibración que la pareja también disfruta.",
    shipping: "Sobres discretos y compactos.",
    warranty: "Sin garantía al ser descartable."
  },
  {
    id: "p18",
    slug: "anillo-vibrador-chester",
    name: "Anillo Vibrador Chester",
    description: "Anillo vibrador de silicona texturada para estimulación extra en penetración.",
    price: 5495,
    images: [],
    category: "Cuidado Masculino",
    collection: "Anillos Vibradores",
    features: ["Texturizado", "Estimulación Clitorial", "Baterías Incluidas", "Reutilizable"],
    details: "Diseño ergonómico y texturizado para que la bala vibradora estimule el clítoris en cada movimiento, mientras prolonga la erección del usuario.",
    shipping: "Envío discreto garantizado.",
    warranty: "Garantía por falla eléctrica."
  },
  {
    id: "p19",
    slug: "vibrador-satisfyer-master",
    name: "Vibrador Satisfyer Master",
    description: "Un poderoso vibrador diseñado para llegar a los puntos más profundos.",
    price: 29995,
    images: [],
    category: "Vibradores",
    collection: "Satisfyer Premium",
    features: ["Silicona ultra suave", "Potente vibración", "Resistente al agua", "Diseño Ergonómico"],
    details: "Combina elegancia, tamaño imponente y la calidad incomparable de Satisfyer. Modos de vibración ajustables desde suaves pulsaciones hasta intensos temblores.",
    shipping: "Envío discreto en embalaje negro.",
    warranty: "1 Año de Garantía del fabricante."
  },
  {
    id: "p20",
    slug: "vibrador-aimi-rabbit",
    name: "Vibrador Aimi Rabbit",
    description: "Lujo total en estimulación dual. Diseño sofisticado, tacto seda.",
    price: 69995,
    images: [],
    category: "Vibradores",
    collection: "Rabbit Deluxe",
    features: ["Silicona Líquida", "Doble Motor Independiente", "Sumergible", "Recargable USB Magnético"],
    details: "La joya de la corona en vibradores tipo conejo. Curvatura perfecta para Punto G y estimulador clitorial flexible. Motores gemelos súper potentes pero extremadamente silenciosos.",
    shipping: "Empaque de lujo, envío 100% confidencial.",
    warranty: "Garantía Silk Deluxe Premium 1 Año."
  },
  {
    id: "p21",
    slug: "lubricante-base-agua-fresco-arctic-chill",
    name: "Lubricante Base Agua Fresco Arctic Chill",
    description: "Efecto frío e intenso para contrastes térmicos emocionantes.",
    price: 4995,
    images: [],
    category: "Lubricantes y Aceites",
    collection: "Sensory Lubes",
    features: ["Efecto Frio", "Base Acuosa", "Seguro con Toys", "Larga Duración"],
    details: "Experimenta escalofríos de placer. Un lubricante de alta calidad con un aditivo especial que proporciona una sensación refrescante e intensifica la sensibilidad.",
    shipping: "Envíos discretos a todo Chile.",
    warranty: "Garantía por embalaje."
  },
  {
    id: "p22",
    slug: "satisfyer-pro-penguin",
    name: "Satisfyer Pro Penguin",
    description: "Estimulador de clítoris por succión en un adorable diseño de pingüino.",
    price: 29995,
    images: [],
    category: "Vibradores",
    collection: "Satisfyer Premium",
    features: ["Ondas Air Pulse", "Súper Discreto/Tierno", "Carga USB", "Resistente IPX7"],
    details: "El clásico más amigable y disfrazado. Sus 11 niveles de ondas de presión garantizan orgasmos rápidos e intensos. Perfecto para regalar.",
    shipping: "Envío seguro y sin marcas.",
    warranty: "1 Año de Garantía Satisfyer."
  }
];
